#lab-sql-joins
USE sakila;

#1.List the number of films per category.
SELECT COUNT(film_id), name
FROM category
INNER JOIN film_category
USING(category_id)
GROUP BY name
ORDER BY COUNT(film_id) DESC;

#2.Retrieve the store ID, city, and country for each store.
SELECT store_id, city, country
FROM store
INNER JOIN address
USING(address_id)
INNER JOIN city
USING(city_id)
INNER JOIN country
USING(country_id);

#3.Calculate the total revenue generated by each store in dollars.
SELECT SUM(amount) as revenue, store_id
FROM payment
INNER JOIN staff
USING (staff_id)
GROUP BY store_id;

#4.Determine the average running time of films for each category.
SELECT category.name, AVG(film.length) AS avg_lenght
FROM film
INNER JOIN film_category
USING(film_id)
INNER JOIN category
USING(category_id)
GROUP BY category.name;

